#pragma once
#define SIMON_WALKING_SPEED		0.07f 
//0.1f
#define SIMON_JUMP_SPEED_Y		0.4f
#define SIMON_GRAVITY			0.002f
#define SIMON_DIE_DEFLECT_SPEED	 0.5f
#define RESET_SIMON_AFTER_SIT 9
#define RESET_SIMON_AFTER_JUMP 9


#define SIMON_STATE_IDLE			0
#define SIMON_STATE_WALKING_RIGHT	100
#define SIMON_STATE_WALKING_LEFT	200
#define SIMON_STATE_JUMP			300
#define SIMON_STATE_DIE				400
#define SIMON_STATE_SIT				500
#define SIMON_STATE_ATTACK			600


#define SIMON_ANI_IDLE_LEFT 0
#define SIMON_ANI_IDLE_RIGHT 1
#define SIMON_ANI_DIE_LEFT 2
#define SIMON_ANI_DIE_RIGHT 3
#define SIMON_ANI_WALKING_LEFT 4
#define SIMON_ANI_WALKING_RIGHT 5
#define SIMON_ANI_SIT_LEFT 6
#define SIMON_ANI_SIT_RIGHT 7
#define SIMON_ANI_ATTACK_LEVEL_1_STAND_LEFT 10
#define SIMON_ANI_ATTACK_LEVEL_1_STAND_RIGHT 11


#define SIMON_BBOX_WIDTH 16
#define SIMON_BBOX_HEIGHT 30

#define SIMON_SIT_BBOX_WIDTH 16
#define SIMON_SIT_BBOX_HEIGHT 23

#define SIMON_WEAPON_LEVEL_1 0
#define SIMON_WEAPON_LEVEL_2 1
#define SIMON_WEAPON_LEVEL_3 2

#define SIMON_RESET_ATTACK_TIME 300 // được đánh sau mỗi 500ms

#define SIMON_RESET_JUMP_TIME  700 // được nhảy sau mỗi 300ms

//Chia sence sau
#define SCENCE_1_MAX_WIDTH 767
