#pragma once
#define SIMON_WALKING_SPEED		0.07f 
//0.1f
#define SIMON_JUMP_SPEED_Y		0.35f
#define SIMON_GRAVITY			0.002f
#define SIMON_DIE_DEFLECT_SPEED	 0.5f
#define RESET_SIMON_AFTER_SIT 9
#define RESET_SIMON_AFTER_JUMP 9
#define OFFSET_FLIP_X 24


#define SIMON_STATE_IDLE			0
#define SIMON_STATE_WALKING_RIGHT	100
#define SIMON_STATE_WALKING_LEFT	200
#define SIMON_STATE_JUMP			300
#define SIMON_STATE_DIE				400
#define SIMON_STATE_SIT				500
#define SIMON_STATE_ATTACK			600
#define SIMON_STATE_HURT		    700
#define SIMON_STATE_THROW			800


#define SIMON_ANI_IDLE 0
#define SIMON_ANI_DIE 0
#define SIMON_ANI_HURT 0
#define SIMON_ANI_THROW 3
#define SIMON_ANI_WALKING 1
#define SIMON_ANI_SIT 2
#define SIMON_ANI_ATTACK 3


#define SIMON_BBOX_WIDTH 16
#define SIMON_BBOX_HEIGHT 30

#define SIMON_SIT_BBOX_WIDTH 16
#define SIMON_SIT_BBOX_HEIGHT 23

#define SIMON_WEAPON_LEVEL_1 0
#define SIMON_WEAPON_LEVEL_2 1
#define SIMON_WEAPON_LEVEL_3 2

#define SIMON_RESET_ATTACK_TIME 400 

#define SIMON_RESET_JUMP_TIME  600

#define SIMON_UNTOUCHABLE_TIME 1000
#define PUSH_SIMON_TOUCH_ENEMIES_X 20
#define PUSH_SIMON_TOUCH_ENEMIES_Y 15
#define PUSH_SIMON_TOUCH_ENEMIES_VY 0.15


//Chia sence sau
#define SCENCE_1_MAX_WIDTH 767
