#pragma once
#define SIMON_WALKING_SPEED		0.07f 
#define SIMON_AUTO_WALKING_SPEED		0.035f 

//0.1f
#define SIMON_JUMP_SPEED_Y		0.35f
#define SIMON_JUMP_ATTACK_SPEED_Y		0.035f
#define SIMON_FALLING_GRAVITY	0.0004f
#define SIMON_GRAVITY			0.002f
#define SIMON_DIE_DEFLECT_SPEED	 0.5f
#define RESET_SIMON_AFTER_SIT 9
#define RESET_SIMON_AFTER_JUMP 9
#define OFFSET_FLIP_X 24


#define SIMON_STATE_IDLE			0
#define SIMON_STATE_WALKING_RIGHT	100
#define SIMON_STATE_WALKING_LEFT	200
#define SIMON_STATE_JUMP			300
#define SIMON_STATE_DIE				400
#define SIMON_STATE_SIT				500
#define SIMON_STATE_ATTACK			600
#define SIMON_STATE_HURT		    700
#define SIMON_STATE_SIT_ATTACK		800
#define SIMON_STATE_FREEZE			900



#define SIMON_ANI_IDLE 0
#define SIMON_ANI_HURT 1 
#define SIMON_ANI_DIE 2
#define SIMON_ANI_WALKING 3
#define SIMON_ANI_SIT 5 
#define SIMON_ANI_ATTACK 7
#define SIMON_ANI_SIT_ATTACK 18
#define SIMON_ANI_FREEZE 17


#define SIMON_BBOX_WIDTH 16
#define SIMON_BBOX_HEIGHT 30

#define SIMON_SIT_BBOX_WIDTH 16
#define SIMON_SIT_BBOX_HEIGHT 23

#define SIMON_WEAPON_LEVEL_1 1
#define SIMON_WEAPON_LEVEL_2 2
#define SIMON_WEAPON_LEVEL_3 3

#define SIMON_RESET_ATTACK_TIME 300 

#define SIMON_RESET_JUMP_TIME  600

#define SIMON_TIME_FREEZE_MAX 1000

#define SIMON_UNTOUCHABLE_TIME 1000
#define PUSH_SIMON_TOUCH_ENEMIES_X 20
#define PUSH_SIMON_TOUCH_ENEMIES_Y 15
#define PUSH_SIMON_TOUCH_ENEMIES_VY 0.15

#define SIMON_START_GAME_POSITION_X 32.0f
#define SIMON_START_GAME_POSITION_Y 163.0f

//Chia sence sau
#define SCENCE_1_MAX_WIDTH 767

enum SIMON_WEAPON {
	NONE,
	WHIP,
	DANGER,
	AXE,
	HOLY_WATER,
	STOP_WATCH
};
enum SIMON_HEART_USE_WEAPON {
	WHIP_HEART = 0,
	DANGER_HEART = 1,
	AXE_HEART = 1,
	HOLY_WATER_HEART = 1,
	STOP_WATCH_HEART = 5
};
